# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'time_track.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(696, 475)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(260, 120, 171, 71))
        self.pushButton.setObjectName("pushButton")
        self.start_time = QtWidgets.QLabel(Form)
        self.start_time.setGeometry(QtCore.QRect(110, 270, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(18)
        self.start_time.setFont(font)
        self.start_time.setStyleSheet("background-color: bisque;")
        self.start_time.setText("")
        self.start_time.setObjectName("start_time")
        self.end_time = QtWidgets.QLabel(Form)
        self.end_time.setGeometry(QtCore.QRect(270, 270, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(18)
        self.end_time.setFont(font)
        self.end_time.setStyleSheet("background-color: bisque;")
        self.end_time.setText("")
        self.end_time.setObjectName("end_time")
        self.elapsed_time = QtWidgets.QLabel(Form)
        self.elapsed_time.setGeometry(QtCore.QRect(430, 270, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(15)
        self.elapsed_time.setFont(font)
        self.elapsed_time.setStyleSheet("background-color: bisque;")
        self.elapsed_time.setText("")
        self.elapsed_time.setObjectName("elapsed_time")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Click me!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
