# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sum.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(482, 403)
        MainWindow.setAnimated(True)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.NUM1 = QtWidgets.QLabel(self.centralwidget)
        self.NUM1.setGeometry(QtCore.QRect(80, 130, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NUM1.sizePolicy().hasHeightForWidth())
        self.NUM1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.NUM1.setFont(font)
        self.NUM1.setMouseTracking(False)
        self.NUM1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NUM1.setObjectName("NUM1")
        self.NUM2 = QtWidgets.QLabel(self.centralwidget)
        self.NUM2.setGeometry(QtCore.QRect(80, 170, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.NUM2.setFont(font)
        self.NUM2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NUM2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.NUM2.setObjectName("NUM2")
        self.RESULT = QtWidgets.QPushButton(self.centralwidget)
        self.RESULT.setGeometry(QtCore.QRect(170, 230, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.RESULT.setFont(font)
        self.RESULT.setMouseTracking(True)
        self.RESULT.setAutoFillBackground(False)
        self.RESULT.setStyleSheet("font: 8pt \"Microsoft YaHei UI\";\n"
        "font: 15pt \"MS Shell Dlg 2\";")
        self.RESULT.setCheckable(False)
        self.RESULT.setAutoRepeat(False)
        self.RESULT.setAutoDefault(False)
        self.RESULT.setDefault(True)
        self.RESULT.setFlat(False)
        self.RESULT.setObjectName("RESULT")
        self.SUM = QtWidgets.QLabel(self.centralwidget)
        self.SUM.setGeometry(QtCore.QRect(60, 280, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.SUM.setFont(font)
        self.SUM.setFrameShape(QtWidgets.QFrame.Box)
        self.SUM.setText("")
        self.SUM.setObjectName("SUM")
        self.plainTextEdi_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdi_1.setGeometry(QtCore.QRect(230, 130, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plainTextEdi_1.setFont(font)
        self.plainTextEdi_1.setObjectName("plainTextEdi_1")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(230, 170, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(170, 70, 141, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 482, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.RESULT.clicked.connect(self.operation)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def operation(self):
        x = int(self.plainTextEdi_1.toPlainText())
        y = int(self.plainTextEdit_2.toPlainText())

        op = self.comboBox.currentText()

        if op == '+':
            self.SUM.setText("Summation: " + str(x + y))
        elif op == '-':
            self.SUM.setText("Substruction: " + str(x - y))
        elif op == '*':
            self.SUM.setText("Multiplication: " + str(x * y))
        elif op == '/':
            self.SUM.setText("Division: " + str(x / y))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NUM1.setText(_translate("MainWindow", "Number 1"))
        self.NUM2.setText(_translate("MainWindow", "Number 2"))
        self.RESULT.setText(_translate("MainWindow", "Get Result"))
        self.comboBox.setItemText(0, _translate("MainWindow", "+"))
        self.comboBox.setItemText(1, _translate("MainWindow", "-"))
        self.comboBox.setItemText(2, _translate("MainWindow", "*"))
        self.comboBox.setItemText(3, _translate("MainWindow", "/"))
        self.label.setText(_translate("MainWindow", "Select Operator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
