# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tictac.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 477)
        font = QtGui.QFont()
        font.setPointSize(15)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainBox = QtWidgets.QGroupBox(self.centralwidget)
        self.MainBox.setGeometry(QtCore.QRect(100, 40, 361, 301))
        self.MainBox.setStyleSheet("border-width: 5px")
        self.MainBox.setTitle("")
        self.MainBox.setObjectName("MainBox")
        self.p1 = QtWidgets.QPushButton(self.MainBox)
        self.p1.setGeometry(QtCore.QRect(0, 0, 121, 101))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.p1.setFont(font)
        self.p1.setStyleSheet("font: 15pt \"Modern No. 20\";")
        self.p1.setText("")
        self.p1.setObjectName("p1")
        self.p2 = QtWidgets.QPushButton(self.MainBox)
        self.p2.setGeometry(QtCore.QRect(120, 0, 121, 101))
        self.p2.setStyleSheet("font: 15pt \"Modern No. 20\";")
        self.p2.setText("")
        self.p2.setObjectName("p2")
        self.p3 = QtWidgets.QPushButton(self.MainBox)
        self.p3.setGeometry(QtCore.QRect(240, 0, 121, 101))
        self.p3.setStyleSheet("font: 15pt \"Modern No. 20\";")
        self.p3.setText("")
        self.p3.setObjectName("p3")
        self.p6 = QtWidgets.QPushButton(self.MainBox)
        self.p6.setGeometry(QtCore.QRect(240, 100, 121, 101))
        self.p6.setStyleSheet("font: 15pt \"Modern No. 20\";")
        self.p6.setText("")
        self.p6.setObjectName("p6")
        self.p5 = QtWidgets.QPushButton(self.MainBox)
        self.p5.setGeometry(QtCore.QRect(120, 100, 121, 101))
        self.p5.setStyleSheet("font: 15pt \"Modern No. 20\";")
        self.p5.setText("")
        self.p5.setObjectName("p5")
        self.p4 = QtWidgets.QPushButton(self.MainBox)
        self.p4.setGeometry(QtCore.QRect(0, 100, 121, 101))
        self.p4.setStyleSheet("font: 15pt \"Modern No. 20\";")
        self.p4.setText("")
        self.p4.setObjectName("p4")
        self.p9 = QtWidgets.QPushButton(self.MainBox)
        self.p9.setGeometry(QtCore.QRect(240, 200, 121, 101))
        self.p9.setStyleSheet("font: 15pt \"Modern No. 20\";")
        self.p9.setText("")
        self.p9.setObjectName("p9")
        self.p8 = QtWidgets.QPushButton(self.MainBox)
        self.p8.setGeometry(QtCore.QRect(120, 200, 121, 101))
        self.p8.setStyleSheet("font: 15pt \"Modern No. 20\";")
        self.p8.setText("")
        self.p8.setObjectName("p8")
        self.p7 = QtWidgets.QPushButton(self.MainBox)
        self.p7.setGeometry(QtCore.QRect(0, 200, 121, 101))
        self.p7.setStyleSheet("font: 15pt \"Modern No. 20\";")
        self.p7.setText("")
        self.p7.setObjectName("p7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 410, 91, 41))
        self.pushButton.setStyleSheet("font: 15pt \"Arial\";")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 350, 361, 31))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.p1.clicked.connect(self.pp1)
        self.p2.clicked.connect(self.pp2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    a = ""
    def pp1(self):
        global a
        a = "a"
        self.label.setText(str(a))
    def pp2(self):
        global a
        a += "b"
        self.label.setText(str(a))


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
