# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(624, 403)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_widget = QtWidgets.QFrame(self.centralwidget)
        self.main_widget.setGeometry(QtCore.QRect(10, 10, 601, 381))
        self.main_widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 49, 148, 255), stop:0.75 rgba(0, 7, 20, 255));\n"
"border-radius: 10px")
        self.main_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_widget.setObjectName("main_widget")
        self.app_name = QtWidgets.QLabel(self.main_widget)
        self.app_name.setGeometry(QtCore.QRect(0, 70, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(40)
        self.app_name.setFont(font)
        self.app_name.setStyleSheet("background-color: none;")
        self.app_name.setObjectName("app_name")
        self.loading = QtWidgets.QLabel(self.main_widget)
        self.loading.setGeometry(QtCore.QRect(0, 310, 601, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.loading.setFont(font)
        self.loading.setStyleSheet("background-color: none;\n"
"")
        self.loading.setObjectName("loading")
        self.app_description = QtWidgets.QLabel(self.main_widget)
        self.app_description.setGeometry(QtCore.QRect(0, 130, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.app_description.setFont(font)
        self.app_description.setStyleSheet("background-color: none;\n"
"")
        self.app_description.setObjectName("app_description")
        self.progressBar = QtWidgets.QProgressBar(self.main_widget)
        self.progressBar.setGeometry(QtCore.QRect(30, 280, 531, 23))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(56, 58, 89);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(114, 170, 9, 255), stop:1 rgba(255, 255, 127, 255));\n"
"\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.app_name.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#bed848;\">Your</span><span style=\" color:#bed848;\"> APP NAME</span></p></body></html>"))
        self.loading.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#7b849f;\">Loading...</span></p></body></html>"))
        self.app_description.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#6272a4;\">App Description</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
